### PR TITLE
Update namespace Renderer to Handler

### PR DESCRIPTION
**Pull request by shyunMin**
### Description of Change ###
This PR is to update namespace name from Renderer to Handler.

### CODE REVIEW

**Review by JoonghyunCho — APPROVED** [review]
good start

**Comment by sung-su** [comment]
I'd like to consider removing the `Forms` suffix to the namespace : )

_Originally posted by @rookiejava in https://github.com/Samsung/Tizen.TV.UIControls/pull/96#discussion_r1092810551_

**Comment by shyunMin** [comment]
> I'd like to consider removing the `Forms` suffix to the namespace : )
> 
> _Originally posted by @rookiejava in [#96 (comment)](https://github.com/Samsung/Tizen.TV.UIControls/pull/96#discussion_r1092810551)_

I think that removing `Forms` suffix is big task, It can occur renaming project and API breaking. I'd like to discuss that including new name until the migration is finished.

**Review by sung-su — APPROVED** [review]
OK, make sense

**Pull request merged**
